export const LOAD_INITIAL_TABLE = 'LOAD_INITIAL_TABLE'
export const ERROR_WHILE_FETCHING_INITIAL_TABLE = 'ERROR_WHILE_FETCHING_INITIAL_TABLE'
export const IF_BUS_STOP_EDIT_MODAL = 'IF_BUS_STOP_EDIT_MODAL'
export const IF_BUS_STOP_TABLE_SHOULD_RENDER = 'IF_BUS_STOP_TABLE_SHOULD_RENDER'
export const LOAD_INITIAL_BUS_STOPS_TABLE = 'LOAD_INITIAL_BUS_STOPS_TABLE'
export const ERROR_WHILE_FETCHING_INITIAL_BUS_STOPS_TABLE =
  'ERROR_WHILE_FETCHING_INITIAL_BUS_STOPS_TABLE'
